#pragma once

//all technical indicators

#include "SMA.hpp"
#include "EMA.hpp"
#include "WMA.hpp"
#include "DEMA.hpp"
#include "TEMA.hpp"
#include "TRIMA.hpp"
#include "KAMA.hpp"
#include "MAMA.hpp"
#include "VWAP.hpp"
#include "T3.hpp"
#include "MACD.hpp"
#include "MACDEXT.hpp"
#include "STOCH.hpp"
#include "STOCHF.hpp"
#include "RSI.hpp"
#include "STOCHRSI.hpp"
#include "WILLR.hpp"
#include "ADX.hpp"
#include "ADXR.hpp"
#include "APO.hpp"
#include "PPO.hpp"
#include "MOM.hpp"
#include "BOP.hpp"
#include "CCI.hpp"
#include "CMO.hpp"
#include "ROC.hpp"
#include "ROCR.hpp"
#include "AROON.hpp"
#include "AROONOSC.hpp"
#include "MFI.hpp"
#include "TRIX.hpp"
